namespace Fantastic.TheMovieDb
{
    using TheMovieDb.Models;
    using System.Text.Json.Serialization;

    [JsonSourceGenerationOptions(WriteIndented = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault | JsonIgnoreCondition.WhenWritingNull)]
    [JsonSerializable(typeof(AccountState))]
    [JsonSerializable(typeof(AlternativeTitle))]
    [JsonSerializable(typeof(AlternativeTitles))]
    [JsonSerializable(typeof(Cast))]
    [JsonSerializable(typeof(Change))]
    [JsonSerializable(typeof(ChangesContainer))]
    [JsonSerializable(typeof(ContentRating))]
    [JsonSerializable(typeof(Country))]
    [JsonSerializable(typeof(CreatedBy))]
    [JsonSerializable(typeof(Credits))]
    [JsonSerializable(typeof(Crew))]
    [JsonSerializable(typeof(Episode))]
    [JsonSerializable(typeof(ExternalIds))]
    [JsonSerializable(typeof(ExternalIdsMovie))]
    [JsonSerializable(typeof(ExternalIdsTvShow))]
    [JsonSerializable(typeof(Genre))]
    [JsonSerializable(typeof(ImageData))]
    [JsonSerializable(typeof(Images))]
    [JsonSerializable(typeof(Keyword))]
    [JsonSerializable(typeof(KeywordsContainer))]
    [JsonSerializable(typeof(ListResult))]
    [JsonSerializable(typeof(Movie))]
    [JsonSerializable(typeof(NetworkBase))]
    [JsonSerializable(typeof(NetworkWithLogo))]
    [JsonSerializable(typeof(ProductionCompany))]
    [JsonSerializable(typeof(ProductionCountry))]
    [JsonSerializable(typeof(ReleaseDateItem))]
    [JsonSerializable(typeof(ReleaseDatesContainer))]
    [JsonSerializable(typeof(Releases))]
    [JsonSerializable(typeof(ReviewBase))]
    [JsonSerializable(typeof(SearchBase))]
    [JsonSerializable(typeof(SearchCollection))]
    [JsonSerializable(typeof(SearchMovie))]
    [JsonSerializable(typeof(SearchMovieTvBase))]
    [JsonSerializable(typeof(SearchTv))]
    [JsonSerializable(typeof(SearchTvSeason))]
    [JsonSerializable(typeof(Season))]
    [JsonSerializable(typeof(Series))]
    [JsonSerializable(typeof(SpokenLanguage))]
    [JsonSerializable(typeof(Translation))]
    [JsonSerializable(typeof(TranslationsContainer))]
    [JsonSerializable(typeof(TvEpisodeBase))]
    [JsonSerializable(typeof(TvEpisodeInfo))]
    [JsonSerializable(typeof(Video))]
    public partial class TheMovieDbSourceGenerationContext : JsonSerializerContext
    {
    }
}
